"""
This module defines the tkTooltipWidget class. It is a tkinter TopLevel window that displays a tooltip message.

Exported Classes:
    tkTooltipWidget -- A tkinter TopLevel window that displays a tooltip message.

Exported Exceptions:
    None    
 
Exported Functions:
    None
"""


# Standard imports
import tkinter as tk
from tkinter import ttk

# Local imports


# TODO: This code was autogenerated by GitHub Copilot. It may need to be modified.
# In particular, hide() may not be needed. Also, the content of the tooltip clould be in an
# a tkXHTMLViewerWidget rather than a Label widget, if formatting is desirable.
class tkTooltipWidget(tk.Toplevel):
    """A tooltip widget that displays a message in a small window when the user hovers over a widget."""
    def __init__(self, parent, text, **kwargs):
        super().__init__(parent, **kwargs)
        self.withdraw()  # Hide the tooltip initially
        self.overrideredirect(True)  # Remove window decorations
        self.label = tk.Label(self, text=text, background="yellow", relief="solid", borderwidth=1)
        self.label.pack(ipadx=1)
    def show(self, x, y):
        """Show the tooltip at the specified (x, y) coordinates."""
        self.geometry(f"+{x}+{y}")
        self.deiconify()  # Show the tooltip
    def hide(self):
        """Hide the tooltip."""
        self.withdraw()
